# Generated by Django 4.2 on 2023-04-20 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoping', '0003_auto_20230417_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
